# Shopify ストアのドメイン
store = "mogu-kyoto.myshopify.com"

# テーマの ID（`shopify theme list` で取得）
theme_id = "175852781868" #simple-themeのID

# アップロードするディレクトリ（通常はプロジェクトルート）
directory = "."

# テーマの名前
name = "simple-theme"

# 自動更新を無効化する（必要に応じて設定）
ignore_files = ["config/settings_data.json", "assets/tailwind.output.css"]
